### ISSUE TITLE
ストリーム処理軽量化

### ISSUE THREAD

**Issue by otofune** [misskey-delta/misskey-api#53]
Redisに直接ぶち込んで神になろう、IDを入れなくても内容は可変じゃないので現状は無駄感すごい

**Comment by Tosuke** [comment]
やるぞ

**Comment by otofune** [comment]
@Tosuke オッ、やりますか？いまからちゃっちゃとやっちゃおうかと思ったんですがやるならアサインします

**Comment by otofune** [comment]
ちょっとやった
https://github.com/misskey-delta/misskey-api/commit/6b01fe0996699a96e58f147dba6f2699ffc5af07

**Comment by Tosuke** [comment]
やっちゃったか

**Comment by otofune** [comment]
ちょっとだけね、今もめっっっっっちゃ重たいのであんまり意味はない

**Comment by otofune** [comment]
スルメが雑にindex貼ってくれたんですがめちゃくちゃ軽くなったので良かったんですが、それはさておき軽量化はしたい
でひとつ感じたのがあって、post.idでshow叩くんじゃなくてシリアライズされてない投稿入れておいてシリアライズ叩くほうがコストが少なそう

**Comment by otofune** [comment]
データベースが重かったので (スロークエリ) インデックス貼ると解消されますね？インデックス自動で貼るようにしませんか？ってところですね
