### ISSUE TITLE
credentialからuserを取得するAPI

### ISSUE THREAD

**Issue by Tosuke** [misskey-delta/misskey-api#56]
[認証](#36)のためにauth serverから直接DB叩かずにuserを取得したい

**Comment by otofune** [comment]
認証サーバーがどうやって連携するかは知らんけどクレデンシャル情報はAPIが持ってないんだから (authに任せるんですよね？) 同しようもないと思うんですが
user-idからスッと取るのはusers/showあたりでやれそう

**Comment by otofune** [comment]
と思ったんですが、クレデンシャルの意味を間違えていて、パスワードとユーザーIDからですよね？Webにすでに実装されてるって状況なのでおそらくAPIは実装済みだと思うんですが

**Comment by otofune** [comment]
ありますあります
https://github.com/misskey-delta/misskey-api/blob/master/src/endpoints/login.ts
